version: "3.8"
services:
  frontend:
    build:
      context: .  # Verwendet das aktuelle Verzeichnis (wo sich das Frontend befindet)
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8081
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    external: true
